name: Conda Installation
# TODO: this should not run on every single push but
# every time we deploy to Conda
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8']

    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          conda install numpy cython

      - name: Install via Conda
        run: |
          conda install -c nostrumbiodiscovery -c eapm -c conda-forge pele_platform --yes

      - name: Test with pytest
        run: |
          mkdir test_conda
          cd test_conda
          python -m pele_platform.main -h
